# Generated by Django 5.2.3 on 2025-07-14 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='khatmaparticipant',
            name='unique_chapter_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='readingsession',
            name='unique_completed_chapter_per_user',
        ),
        migrations.AlterField(
            model_name='khatmaparticipant',
            name='chapter_assigned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddConstraint(
            model_name='khatmaparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_assigned__isnull', False)), fields=('khatma', 'chapter_assigned'), name='unique_chapter_assignment'),
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(fields=('khatma', 'user', 'chapter_assigned'), name='unique_chapter_per_user_per_khatma'),
        ),
        migrations.AddField(
            model_name='intention',
            name='khatma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to='api.khatma'),
        ),
        migrations.AddField(
            model_name='intention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
