# Generated by Django 5.2.3 on 2025-07-02 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intenstion', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to='api.khatma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
