# Generated by Django 5.2.3 on 2025-07-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_intention'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intention',
            old_name='intenstion',
            new_name='intention',
        ),
    ]
