# Generated by Django 5.2.3 on 2025-07-11 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_intenstion_intention_intention'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='khatmaparticipant',
            name='unique_chapter_assignment',
        ),
        migrations.AlterField(
            model_name='khatmaparticipant',
            name='chapter_assigned',
            field=models.IntegerField(help_text='0 for creator/no specific assignment, 1-30 for specific chapters', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddConstraint(
            model_name='khatmaparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_assigned__gt', 0)), fields=('khatma', 'chapter_assigned'), name='unique_chapter_assignment'),
        ),
    ]
