# Generated by Django 5.2.3 on 2025-07-11 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_khatmaparticipant_unique_chapter_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='khatmaparticipant',
            name='unique_chapter_assignment',
        ),
        migrations.AlterField(
            model_name='khatmaparticipant',
            name='chapter_assigned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddConstraint(
            model_name='khatmaparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('chapter_assigned__isnull', False)), fields=('khatma', 'chapter_assigned'), name='unique_chapter_assignment'),
        ),
    ]
