# Generated by Django 5.2.3 on 2025-07-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_khatmaparticipant_unique_chapter_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readingsession',
            name='unique_completed_chapter_per_user',
        ),
        migrations.AddConstraint(
            model_name='readingsession',
            constraint=models.UniqueConstraint(fields=('khatma', 'user', 'chapter_assigned'), name='unique_chapter_per_user_per_khatma'),
        ),
    ]
